services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: react-frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    container_name: node-backend
    dns:
      - 178.22.122.100
      - 185.51.200.2
